name: Feature Request
description: Suggest an idea for button-card
labels: ["FR"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What need isn't covered? Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.
